FROM python:3.9-alpine

RUN \
    mkdir /root/.Decision_Support_System/ && \
    mkdir /app/ && \
    mkdir /app/Decision_Support_System && \
    mkdir /app/pip_cache

# Installing Oracle instant client
RUN apk --no-cache add libaio libnsl libc6-compat curl && \
    cd /tmp && \
    curl -o instantclient-basiclite.zip https://download.oracle.com/otn_software/linux/instantclient/instantclient-basiclite-linuxx64.zip -SL && \
    unzip instantclient-basiclite.zip && \
    mv instantclient*/ /usr/lib/instantclient && \
    rm instantclient-basiclite.zip && \
    ln -s /usr/lib/instantclient/libclntsh.so.19.1 /usr/lib/libclntsh.so && \
    ln -s /usr/lib/instantclient/libocci.so.19.1 /usr/lib/libocci.so && \
    ln -s /usr/lib/instantclient/libociicus.so /usr/lib/libociicus.so && \
    ln -s /usr/lib/instantclient/libnnz19.so /usr/lib/libnnz19.so && \
    ln -s /usr/lib/libnsl.so.2 /usr/lib/libnsl.so.1 && \
    ln -s /lib/libc.so.6 /usr/lib/libresolv.so.2 && \
    ln -s /lib64/ld-linux-x86-64.so.2 /usr/lib/ld-linux-x86-64.so.2

ENV ORACLE_BASE /usr/lib/instantclient
ENV LD_LIBRARY_PATH /usr/lib/instantclient
ENV TNS_ADMIN /usr/lib/instantclient
ENV ORACLE_HOME /usr/lib/instantclient

# nginx setup
RUN apk add nginx nano unzip -y --no-install-recommends
COPY nginx.default /etc/nginx/sites-available/default
RUN ln -sf /dev/stdout /var/log/nginx/access.log && \
    ln -sf /dev/stderr /var/log/nginx/error.log && \
    nginx -t

# Copy required files and directory
WORKDIR /app
COPY requirements.txt start-server.sh /app/
COPY ./Decision_Support_System /app/Decision_Support_System/

RUN apk add python3-dev gcc libsasl2-dev libldap2-dev libssl-dev g++ -y && \
    apk add libxml2-dev libxmlsec1-dev pkg-config -y && \
    apk add tree && \
    pip install --upgrade pip && \
    pip install -r requirements.txt --cache-dir /app/pip_cache && \
    rm requirements.txt && \
    mv /app/Decision_Support_System/DSS/static/DSS/config /root/.Decision_Support_System/ && \
    cd /app/Decision_Support_System && \
    python setup.py build_ext --inplace && \
    python setup.py bdist_wheel && \
    rm -rf Decision_Support_System DSS && \
    unzip dist/python-1*.whl -d . && \
    rm -rf build dist python-1.* python.e* && \
    tree

EXPOSE 7000

CMD ["/app/start-server.sh"]