
password.defaultUserPassword = 'changeit'

signal.scaColumnListAdhoc = [[name: "flags", display: "Flags", dataType: 'java.lang.String'],
                             [name: "priority.id", display: "Priority", dataType: 'java.lang.String'],
                             [name: "productName", display: "Product Name", dataType: 'java.lang.String'],
                             [name: "ptList", display: "All PTs (SUR)", isAutocomplete: true, dataType: 'java.lang.String'],
                             [name: "conComitList", display: "All Conmeds", isAutocomplete: true, dataType: 'java.lang.String'],
                             [name: "caseInitReceiptDate", display: "Receipt Date", dataType: 'java.util.Date'],
                             [name: "lockedDate", display: "Locked Date", dataType: 'java.util.Date'],
                             [name: "listedness", display: "Listedness", dataType: 'java.lang.String'],
                             [name: "outcome", display: "Outcome", dataType: 'java.lang.String'],
                             [name: "serious", display: "${-> grails.util.Holders?.config?.custom?.caseInfoMap?.Enabled?'Serious/Non-Serious':'Serious'}", dataType: 'java.lang.String'],
                             [name: "caseReportType", display: "Report Type", dataType: 'java.lang.String'],
                             [name: "country", display: "${-> grails.util.Holders?.config?.custom?.caseInfoMap?.Enabled?'Derived Country':'Country'}", dataType: 'java.lang.String'],
                             [name: "reportersHcpFlag", display: "HCP", dataType: 'java.lang.String'],
                             [name: "death", display: "Death", dataType: 'java.lang.String'],
                             [name: "age", display: "Age Group", dataType: 'java.lang.String'],
                             [name: "gender", display: "Gender", dataType: 'java.lang.String'],
                             [name: "caseType", display: "Case Type", dataType: 'java.lang.String'],
                             [name: "completenessScore", display: "Completeness Score", dataType: 'java.lang.Number'],
                             [name: "indNumber", display: "Primary IND#",isAutocomplete: true, dataType: 'java.lang.String'],
                             [name: "appTypeAndNum", display: "Application#", dataType: 'java.lang.String'],
                             [name: "compoundingFlag", display: "Compounding Flag", dataType: 'java.lang.String'],
                             [name: "medErrorPtList", display: "Medication Error PTs", isAutocomplete: true, dataType: 'java.lang.String'],
                             [name: "patientAge", display: "Age", dataType: 'java.lang.Number'],
                             [name: "suspectProductList", display: "All Suspect Products", isAutocomplete: true, dataType: 'java.lang.String'],
                             [name: "rechallenge", display: "Rechallenge", dataType: 'java.lang.String'],
                             [name: "caseNumber", display: "Case(f/u#)", isAutocomplete: true, dataType: 'java.lang.String'],
                             [name: "pt", display: "PT", isAutocomplete: true, dataType: 'java.lang.String'],
                             [name: "caseNarrative", display: "Case Narrative", dataType: 'java.lang.String'],
                             [name: "name", display: "Alert Name", dataType: 'java.lang.String'],
                             [name: "submitter", display: "Submitter", dataType: 'java.lang.String'],
                             [name: "tags", display: "Categories", dataType: 'java.lang.String'],
                             [name: "subTags", display: "Sub Categories", dataType: 'java.lang.String'],
                             [name: "currentRun", display: "Current Period Category", dataType: 'java.lang.Boolean'],
                             [name: "malfunction", display: "Malfunction", dataType: 'java.lang.String'],
                             [name: "comboFlag", display: "Combo Flag", dataType: 'java.lang.String'],
                             [name: "caseSeries", display: "Case Series", isAutocomplete: true,dataType: 'java.lang.String'],
                             [name: "indication", display: "Indication",isAutocomplete: true , dataType: 'java.lang.String'],
                             [name: "eventOutcome", display: "Event  Outcome",isAutocomplete: true , dataType: 'java.lang.String'],
                             [name: "causeOfDeath", display: "Cause of Death",isAutocomplete: true , dataType: 'java.lang.String'],
                             [name: "seriousUnlistedRelated", display: "SUR",isAutocomplete: true , dataType: 'java.lang.String'],
                             [name: "patientMedHist", display: "Patient Med Hist",isAutocomplete: true , dataType: 'java.lang.String'],
                             [name: "patientHistDrugs", display: "Patient Hist Drugs",isAutocomplete: true , dataType: 'java.lang.String'],
                             [name: "batchLotNo", display: "Batch/Lot#",isAutocomplete: true , dataType: 'java.lang.String'],
                             [name: "timeToOnset", display: "Time To Onset" , dataType: 'java.lang.Number'],
                             [name: "caseClassification", display: "Case Classification",isAutocomplete: true , dataType: 'java.lang.String'],
                             [name: "initialFu", display: "Initial/F/u",isAutocomplete: true , dataType: 'java.lang.String'],
                             [name: "protocolNo", display: "Protocol#",isAutocomplete: true , dataType: 'java.lang.String'],
                             [name: "isSusar", display: "SUSAR", dataType: 'java.lang.String'],
                             [name: "therapyDates", display: "Therapy Dates",isAutocomplete: true , dataType: 'java.lang.String'],
                             [name: "doseDetails", display: "Dose Details",isAutocomplete: true , dataType: 'java.lang.String'],
                             [name: "preAnda", display: "Pre-ANDA",isAutocomplete: true , dataType: 'java.lang.String'],
                             [name: "primSuspProdList", display: "Primary Suspect Product", isAutocomplete: true, dataType: 'java.lang.String'],
                             [name: "primSuspPaiList", display: "Primary Suspect PAI", isAutocomplete: true, dataType: 'java.lang.String'],
                             [name: "paiAllList", display: "All Suspect PAIs", isAutocomplete: true, dataType: 'java.lang.String'],
                             [name: "allPtList", display: "All PTs", isAutocomplete: true, dataType: 'java.lang.String'],
                             [name: "dispLastChange", display: "Last Disposition Date", dataType: 'java.util.Date'],
                             [name: "comments", display: "Comments", dataType: 'java.lang.String'],
                             [name: "genericName", display: "Generic Name (Suspect)",isAutocomplete: true , dataType: 'java.lang.String'],
                             [name: "caseCreationDate", display: "Case Creation Date", dataType: 'java.util.Date'],
                             [name: "dateOfBirth", display: "DOB",isAutocomplete: true , dataType: 'java.lang.String'],
                             [name: "eventOnsetDate", display: "Event Onset Date" ,isAutocomplete: true , dataType: 'java.lang.String'],
                             [name: "pregnancy", display: "Pregnancy",isAutocomplete: true , dataType: 'java.lang.String'],
                             [name: "medicallyConfirmed", display: "Medically Confirmed",isAutocomplete: true , dataType: 'java.lang.String'],
                             [name: "allPTsOutcome", display: "All PTs - Outcome",isAutocomplete: true , dataType: 'java.lang.String'],
                             [name: "region", display: "Region", dataType: 'java.lang.String'],
                             [name: "crossReferenceInd", display: "Cross Reference IND",isAutocomplete: true , dataType: 'java.lang.String']
]


configurations.scaColumnOrderListDrilldown = [
        ["containerView": 1, "label": com.rxlogix.Constants.Commons.TAG, "name": "alertTags", isFilter: true, availability: com.rxlogix.Constants.SingleCaseViewAvailability.ALL],
        ["containerView": 1, "label": "Receipt Date", "name": "caseInitReceiptDate", isFilter: true, availability: com.rxlogix.Constants.SingleCaseViewAvailability.ALL],
        ["containerView": 1, "label": "Product Name", "name": "productName", isFilter: true, availability: com.rxlogix.Constants.SingleCaseViewAvailability.ALL],
        ["containerView": 1, "label": "PT", "name": "pt", isFilter: true, availability: com.rxlogix.Constants.SingleCaseViewAvailability.ALL],
        ["containerView": 1, "label": "Listedness", "name": "listedness", isFilter: true, availability: com.rxlogix.Constants.SingleCaseViewAvailability.ALL],
        ["containerView": 1, "label": "Outcome", "name": "outcome", isFilter: true, availability: com.rxlogix.Constants.SingleCaseViewAvailability.ALL],
        ["containerView": 3, "label": "All Suspect Products", "name": "suspProd", isFilter: false, availability: com.rxlogix.Constants.SingleCaseViewAvailability.ALL],
        ["containerView": 3, "label": "All Conmeds", "name": "conComit", isFilter: false, availability: com.rxlogix.Constants.SingleCaseViewAvailability.ALL],
        ["containerView": 3, "label": "All PTs (SUR)", "name": "masterPrefTermAll", isFilter: false, availability: com.rxlogix.Constants.SingleCaseViewAvailability.ALL],
        ["containerView": 1, "label": "${-> grails.util.Holders?.config?.custom?.caseInfoMap?.Enabled?'Serious/Non-Serious':'Serious'}", "name": "serious", isFilter: true, availability: com.rxlogix.Constants.SingleCaseViewAvailability.ALL],
        ["containerView": 3, "label": "Report Type", "name": "caseReportType", isFilter: true, availability: com.rxlogix.Constants.SingleCaseViewAvailability.ALL],
        ["containerView": 3, "label": "HCP", "name": "reportersHcpFlag", isFilter: true, availability: com.rxlogix.Constants.SingleCaseViewAvailability.ALL],
        ["containerView": 3, "label": "${-> grails.util.Holders?.config?.custom?.caseInfoMap?.Enabled?'Derived Country':'Country'}", "name": "country", isFilter: true, availability: com.rxlogix.Constants.SingleCaseViewAvailability.ALL],
        ["containerView": 3, "label": "Age Group", "name": "age", isFilter: true, availability: com.rxlogix.Constants.SingleCaseViewAvailability.ALL],
        ["containerView": 3, "label": "Gender", "name": "gender", isFilter: true, availability: com.rxlogix.Constants.SingleCaseViewAvailability.ALL],
        ["containerView": 3, "label": "Rechallenge", "name": "rechallenge", isFilter: true, availability: com.rxlogix.Constants.SingleCaseViewAvailability.ALL],
        ["containerView": 3, "label": "Locked Date", "name": "lockedDate", isFilter: true, availability: com.rxlogix.Constants.SingleCaseViewAvailability.ALL],
        ["containerView": 3, "label": "Death", "name": "death", isFilter: true, availability: com.rxlogix.Constants.SingleCaseViewAvailability.ALL],
        ["containerView": 3, "label": "Age", "name": "patientAge", isFilter: true, availability: com.rxlogix.Constants.SingleCaseViewAvailability.ALL],
        ["containerView": 3, "label": "Medication Error PTs", "name": "medErrorsPt", isFilter: true, availability: com.rxlogix.Constants.SingleCaseViewAvailability.ONLY_FDA],
        ["containerView": 3, "label": "Case Type", "name": "caseType", isFilter: true, availability: com.rxlogix.Constants.SingleCaseViewAvailability.ONLY_FDA],
        ["containerView": 3, "label": "Completeness Score", "name": "completenessScore", isFilter: true, availability: com.rxlogix.Constants.SingleCaseViewAvailability.ONLY_FDA],
        ["containerView": 3, "label": "Primary IND#", "name": "indNumber", isFilter: true, availability: com.rxlogix.Constants.SingleCaseViewAvailability.ONLY_FDA],
        ["containerView": 3, "label": "Application#", "name": "appTypeAndNum", isFilter: true, availability: com.rxlogix.Constants.SingleCaseViewAvailability.ONLY_FDA],
        ["containerView": 3, "label": "Compounding Flag", "name": "compoundingFlag", isFilter: true, availability: com.rxlogix.Constants.SingleCaseViewAvailability.ONLY_FDA],
        ["containerView": 3, "label": "Submitter", "name": "submitter", isFilter: true, availability: com.rxlogix.Constants.SingleCaseViewAvailability.ONLY_FDA],
        ["containerView": 3, "label": "Malfunction", "name": "malfunction", isFilter: true, availability: com.rxlogix.Constants.SingleCaseViewAvailability.ALL],
        ["containerView": 3, "label": "Combo Flag", "name": "comboFlag", isFilter: true, availability: com.rxlogix.Constants.SingleCaseViewAvailability.ALL],
        ["containerView": 1, "label": "Indication", "name": "indication", isFilter: true, availability: com.rxlogix.Constants.SingleCaseViewAvailability.ALL],
        ["containerView": 1, "label": "Event  Outcome", "name": "eventOutcome", isFilter: true, availability: com.rxlogix.Constants.SingleCaseViewAvailability.ALL],
        ["containerView": 1, "label": "Cause of Death", "name": "causeOfDeath", isFilter: true, availability: com.rxlogix.Constants.SingleCaseViewAvailability.ALL],
        ["containerView": 1, "label": "SUR", "name": "seriousUnlistedRelated", isFilter: true, availability: com.rxlogix.Constants.SingleCaseViewAvailability.ALL],
        ["containerView": 3, "label": "Batch/Lot#", "name": "batchLotNo", isFilter: true, availability: com.rxlogix.Constants.SingleCaseViewAvailability.ALL],
        ["containerView": 3, "label": "Initial/F/u", "name": "initialFu", isFilter: true, availability: com.rxlogix.Constants.SingleCaseViewAvailability.ALL],
        ["containerView": 3, "label": "Case Classification", "name": "caseClassification", isFilter: true, availability: com.rxlogix.Constants.SingleCaseViewAvailability.ALL],
        ["containerView": 3, "label": "Patient Med Hist", "name": "patientMedHist", isFilter: true, availability: com.rxlogix.Constants.SingleCaseViewAvailability.ALL],
        ["containerView": 3, "label": "Patient Hist Drugs", "name": "patientHistDrugs", isFilter: true, availability: com.rxlogix.Constants.SingleCaseViewAvailability.ALL],
        ["containerView": 3, "label": "Time To Onset", "name": "timeToOnset", isFilter: true, availability: com.rxlogix.Constants.SingleCaseViewAvailability.ALL],
        ["containerView": 3, "label": "Protocol#", "name": "protocolNo", isFilter: true, availability: com.rxlogix.Constants.SingleCaseViewAvailability.ALL],
        ["containerView": 3, "label": "SUSAR", "name": "isSusar", isFilter: true, availability: com.rxlogix.Constants.SingleCaseViewAvailability.ALL],
        ["containerView": 3, "label": "Therapy Dates", "name": "therapyDates", isFilter: false, availability: com.rxlogix.Constants.SingleCaseViewAvailability.ALL],
        ["containerView": 3, "label": "Dose Details", "name": "doseDetails", isFilter: false, availability: com.rxlogix.Constants.SingleCaseViewAvailability.ALL],
        ["containerView": 3, "label": "Pre-ANDA", "name": "preAnda", isFilter: true, availability: com.rxlogix.Constants.SingleCaseViewAvailability.ONLY_FDA],
        ["containerView": 3, "label": "Comments", "name": "comments", isFilter: true, availability: com.rxlogix.Constants.SingleCaseViewAvailability.ALL],
        ["containerView": 3, "label": "Primary Suspect Product", "name": "primSuspProd", isFilter: true, availability: com.rxlogix.Constants.SingleCaseViewAvailability.ALL],
        ["containerView": 3, "label": "Primary Suspect PAI", "name": "primSuspPai", isFilter: true, availability: com.rxlogix.Constants.SingleCaseViewAvailability.ONLY_FDA],
        ["containerView": 3, "label": "All Suspect PAIs", "name": "paiAll", isFilter: false, availability: com.rxlogix.Constants.SingleCaseViewAvailability.ONLY_FDA],
        ["containerView": 3, "label": "All PTs", "name": "allPt", isFilter: false, availability: com.rxlogix.Constants.SingleCaseViewAvailability.ALL],
//            ["containerView": 3, "label": "Changes", "name": "changes", isFilter: true, availability: com.rxlogix.Constants.SingleCaseViewAvailability.ONLY_SAFETY],
        ["containerView": 3, "label": "Generic Name (Suspect)", "name": "genericName", isFilter: true, availability: com.rxlogix.Constants.SingleCaseViewAvailability.ONLY_SAFETY],
        ["containerView": 3, "label": "Case Creation Date", "name": "caseCreationDate", isFilter: true, availability: com.rxlogix.Constants.SingleCaseViewAvailability.ONLY_SAFETY],
        ["containerView": 3, "label": "DOB", "name": "dateOfBirth", isFilter: true, availability: com.rxlogix.Constants.SingleCaseViewAvailability.ONLY_SAFETY],
        ["containerView": 3, "label": "Event Onset Date", "name": "eventOnsetDate", isFilter: true, availability: com.rxlogix.Constants.SingleCaseViewAvailability.ONLY_SAFETY],
        ["containerView": 3, "label": "Pregnancy", "name": "pregnancy", isFilter: true, availability: com.rxlogix.Constants.SingleCaseViewAvailability.ONLY_SAFETY],
        ["containerView": 3, "label": "Medically Confirmed", "name": "medicallyConfirmed", isFilter: true, availability: com.rxlogix.Constants.SingleCaseViewAvailability.ONLY_SAFETY],
        ["containerView": 3, "label": "All PTs - Outcome", "name": "allPTsOutcome", isFilter: true, availability: com.rxlogix.Constants.SingleCaseViewAvailability.ONLY_SAFETY],
        ["containerView": 3, "label": "Cross Reference IND", "name": "crossReferenceInd", isFilter: true, availability: com.rxlogix.Constants.SingleCaseViewAvailability.ONLY_FDA]
]

signal.boot.status = false

signal.agaOnDemandColumnList.faers = [[name: "productName", display: "Product Name", dataType: 'java.lang.String'],
                                      [name: "soc", display: "SOC", dataType: 'java.lang.String'],
                                      [name: "listed", display: "Listed", dataType: 'java.lang.String'],
                                      [name: "positiveRechallenge", display: "+ve Rechallenge", dataType: 'java.lang.String'],
                                      [name: "positiveDechallenge", display: "+ve Dechallenge", dataType: 'java.lang.String'],
                                      [name: "related", display: "Related", dataType: 'java.lang.String'],
                                      [name: "pregnancy", display: "Pregnancy", dataType: 'java.lang.String'],
                                      [name: "newSponCount", display: "New Spon", dataType: 'java.lang.Number'],
                                      [name: "cumSponCount", display: "Cum Spon", dataType: 'java.lang.Number'],
                                      [name: "newSeriousCount", display: "New Ser", dataType: 'java.lang.Number'],
                                      [name: "cumSeriousCount", display: "Cum Ser", dataType: 'java.lang.Number'],
                                      [name: "newStudyCount", display: "New Study", dataType: 'java.lang.Number'],
                                      [name: "cumStudyCount", display: "Cum Study", dataType: 'java.lang.Number'],
                                      [name: "newFatalCount", display: "New Fatal", dataType: 'java.lang.Number'],
                                      [name: "cumFatalCount", display: "Cum Fatal", dataType: 'java.lang.Number'],
                                      [name: "newGeriatricCount", display: "New Geria", dataType: 'java.lang.Number'],
                                      [name: "cumGeriatricCount", display: "Cum Geria", dataType: 'java.lang.Number'],
                                      [name: "newNonSerious", display: "${-> grails.util.Holders?.config?.signal?.new?.serious?.column?.header}", dataType: 'java.lang.Number'],
                                      [name: "cumNonSerious", display: "${-> grails.util.Holders?.config?.signal?.cum?.serious?.column?.header}", dataType: 'java.lang.Number'],
                                      [name: "eb05", display: "EB05", dataType: 'java.lang.Number'],
                                      [name: "eb95", display: "EB95", dataType: 'java.lang.Number'],
                                      [name: "ebgm", display: "EBGM", dataType: 'java.lang.Number'],
                                      [name: "prrValue", display: "PRR", dataType: 'java.lang.Number'],
                                      [name: "prrLCI", display: "PRR LCI", dataType: 'java.lang.Number'],
                                      [name: "prrUCI", display: "PRR UCI", dataType: 'java.lang.Number'],
                                      [name: "rorValue", display: "ROR", dataType: 'java.lang.Number'],
                                      [name: "rorLCI", display: "ROR LCI", dataType: 'java.lang.Number'],
                                      [name: "rorUCI", display: "ROR UCI", dataType: 'java.lang.Number'],
                                      [name: "pt", display: "PT/SMQ/Event Group", isAutocomplete: true, dataType: 'java.lang.String'],
                                      [name: "newCount", display: "New Count", dataType: 'java.lang.Number'],
                                      [name: "cummCount", display: "Cum Count", dataType: 'java.lang.Number'],
                                      [name: "newPediatricCount", display: "New Paed", dataType: 'java.lang.Number'],
                                      [name: "cummPediatricCount", display: "Cum Paed", dataType: 'java.lang.Number'],
                                      [name: "newInteractingCount", display: "New Interacting", dataType: 'java.lang.Number'],
                                      [name: "cummInteractingCount", display: "Cum Interacting", dataType: 'java.lang.Number'],
                                      [name: "name", display: "Alert Name", dataType: 'java.lang.String'],
                                      [name: "aggImpEventList", display: "IMP Events", dataType: 'java.lang.String'],
                                      [name: "chiSquare", display: "Chi-Square", dataType: 'java.lang.Number'],
                                      [name: "tags", display: "Categories", dataType: 'java.lang.String'],
                                      [name: "subTags", display: "Sub Categories", dataType: 'java.lang.String'],
                                      [name: "currentRun", display: "Current Period Category", dataType: 'java.lang.Boolean']
]

signal.agg.trend.flag.logic = """ 
                                if(alert.cummCount >= 3 && alert.prrValue >= 2 && alert.chiSquare >= 4){
                                        if(firstEncounter){
                                            "NEW"
                                        } else if(NVL(alert.freqPeriod,alert.cumFreqPeriod) > 1.5 * NVL(alert.reviewedFreqPeriod,alert.reviewedCumFreqPeriod)){
                                            "YES"
                                        } else {
                                            "NO"
                                        }
                                 } else {
                                    "NO"
                                 }
                            """




signalManagement {
    productSummary.enabled = false
}

configurations {
    viewInstances = [
            // Add Fixed Columns Without Priority and Flags, add priorityRequired, flagRequired according to requirement.
            [name: "System View", alertType: "Single Case Alert", filters: "{}", sorting: "{}", defaultValue: true, "columnList": "scaColumnOrderList", "cumulative": false, "fixedColumns": 4,"priorityRequired":true,"flagRequired":true],
            [name: "System View", alertType: "Single Case Alert - DrillDown", filters: "{}", sorting: "{}", defaultValue: true, "columnList": "scaColumnOrderList", "cumulative": false, "fixedColumns": 4,"priorityRequired":true,"flagRequired":false],
            [name: "System View", alertType: "Single Case Alert - Adhoc DrillDown", filters: "{}", sorting: "{}", defaultValue: true, "columnList": "scaColumnOrderListDrilldown", "cumulative": false, "fixedColumns": 4,"priorityRequired":true,"flagRequired":false],
            [name: "System View", alertType: "Single Case Alert - Dashboard", filters: "{}", sorting: "{}", defaultValue: true, "columnList": "scaColumnOrderList", "cumulative": false, "fixedColumns": 5,"priorityRequired":true,"flagRequired":true],
            [name: "System View", alertType: "Single Case Alert - Cumulative", filters: "{}", sorting: "{}", defaultValue: true, "columnList": "scaColumnOrderList", "cumulative": true, "fixedColumns": 6],
            [name: "System View", alertType: "Single Case Alert - Faers", filters: "{}", sorting: "{}", defaultValue: true, "columnList": "scaFaersColumnOrderList", "cumulative": true, "fixedColumns": 3],
            [name: "System View", alertType: "Single Case Alert - Vaers", filters: "{}", sorting: "{}", defaultValue: true, "columnList": "scaVaersColumnOrderList", "cumulative": true, "fixedColumns": 3],
            [name: "System View", alertType: "Single Case Alert - Vigibase", filters: "{}", sorting: "{}", defaultValue: true, "columnList": "scaVigibaseColumnOrderList", "cumulative": true, "fixedColumns": 3],
            [name: "System View", alertType: "Single Case Alert - Jader", filters: "{}", sorting: "{}", defaultValue: true, "columnList": "scaJaderColumnOrderList", "cumulative": true, "fixedColumns": 3],
            [name: "System View", alertType: "Aggregate Case Alert", filters: "{}", sorting: "{}", defaultValue: true, "columnList": "agaColumnOrderList", "cumulative": false, "fixedColumns": 6,"priorityRequired":true,"flagRequired":true],
            [name: "System View", alertType: "Aggregate Case Alert - FAERS", filters: "{}", sorting: "{}", defaultValue: true, "columnList": "agaColumnOrderList", "cumulative": false, "fixedColumns": 6,"priorityRequired":true,"flagRequired":true],
            [name: "System View", alertType: "Aggregate Case Alert - Dashboard", filters: "{}", sorting: "{}", defaultValue: true, "columnList": "agaColumnOrderList", "cumulative": false, "fixedColumns": 7,"priorityRequired":true,"flagRequired":true],
            [name: "System View", alertType: "Aggregate Case Alert - Cumulative", filters: "{}", sorting: "{}", defaultValue: true, "columnList": "agaColumnOrderList", "cumulative": true, "fixedColumns": 9],
            [name: "System View", alertType: "Aggregate Case Alert - SMQ FAERS", filters: "{}", sorting: "{}", defaultValue: true, "columnList": "agaGroupBySMQColumnOrderList", "cumulative": true, "fixedColumns": 5,"priorityRequired":true,"flagRequired":true],
            [name: "System View", alertType: "Aggregate Case Alert - SMQ", filters: "{}", sorting: "{}", defaultValue: true, "columnList": "agaGroupBySMQColumnOrderList", "cumulative": true, "fixedColumns": 5,"priorityRequired":true,"flagRequired":true],
            [name: "System View", alertType: "EVDAS Alert", filters: "{}", sorting: "{}", defaultValue: true, "columnList": "evdasColumnOrderList", "cumulative": false, "fixedColumns": 6,"priorityRequired":true,"flagRequired":true],
            [name: "System View", alertType: "EVDAS Alert - Cumulative", filters: "{}", sorting: "{}", defaultValue: true, "columnList": "evdasColumnOrderList", "cumulative": true, "fixedColumns": 9],
            [name: "System View", alertType: "EVDAS Alert - Dashboard", filters: "{}", sorting: "{}", defaultValue: true, "columnList": "evdasColumnOrderList", "cumulative": false, "fixedColumns": 7,"priorityRequired":true,"flagRequired":true],
            [name: "System View", alertType: "Adhoc Alert", filters: "{}", sorting: "{}", defaultValue: true, "columnList": "adhocColumnOrderList", "cumulative": true, "fixedColumns": 3,"priorityRequired":true,"flagRequired":false],
            [name: "System View", alertType: "Signal Management", filters: "{}", sorting: "{}", defaultValue: true, "columnList": "signalColumnOrderList", "cumulative": true, "fixedColumns": 2],
            [name: "System View", alertType: "Literature Search Alert", filters: "{}", sorting: "{}", defaultValue: true, "columnList": "literatureColumnOrderList", "cumulative": true, "fixedColumns": 3,"priorityRequired":true,"flagRequired":false],
            [name: "System View", alertType: "Aggregate Case Alert on Demand", filters: "{}", sorting: "{}", defaultValue: true, "columnList": "agaColumnOrderListOnDemand", "cumulative": false, "fixedColumns": 4],
            [name: "System View", alertType: "Aggregate Case Alert on Demand - FAERS", filters: "{}", sorting: "{}", defaultValue: true, "columnList": "agaColumnOrderListOnDemandFaers", "cumulative": false, "fixedColumns": 4],
            [name: "System View", alertType: "Aggregate Case Alert - SMQ on Demand", filters: "{}", sorting: "{}", defaultValue: true, "columnList": "agaGroupBySMQColumnOrderListonDemand", "cumulative": true, "fixedColumns": 3],
            [name: "System View", alertType: "Aggregate Case Alert - SMQ on Demand FAERS", filters: "{}", sorting: "{}", defaultValue: true, "columnList": "agaGroupBySMQColumnOrderListonDemandFaers", "cumulative": true, "fixedColumns": 3],
            [name: "System View", alertType: "Aggregate Case Alert on Demand - VAERS", filters: "{}", sorting: "{}", defaultValue: true, "columnList": "agaColumnOrderListOnDemandVaers", "cumulative": false, "fixedColumns": 4],
            [name: "System View", alertType: "Aggregate Case Alert - SMQ on Demand VAERS", filters: "{}", sorting: "{}", defaultValue: true, "columnList": "agaGroupBySMQColumnOrderListonDemandVaers", "cumulative": true, "fixedColumns": 3],
            [name: "System View", alertType: "Aggregate Case Alert on Demand - VIGIBASE", filters: "{}", sorting: "{}", defaultValue: true, "columnList": "agaColumnOrderListOnDemandVigibase", "cumulative": false, "fixedColumns": 4],
            [name: "System View", alertType: "Aggregate Case Alert - SMQ on Demand VIGIBASE", filters: "{}", sorting: "{}", defaultValue: true, "columnList": "agaGroupBySMQColumnOrderListonDemandVigibase", "cumulative": true, "fixedColumns": 3],
            [name: "System View", alertType: "Aggregate Case Alert on Demand - JADER", filters: "{}", sorting: "{}", defaultValue: true, "columnList": "agaColumnOrderListOnDemandJader", "cumulative": false, "fixedColumns": 4],
            [name: "System View", alertType: "Aggregate Case Alert - SMQ on Demand JADER", filters: "{}", sorting: "{}", defaultValue: true, "columnList": "agaGroupBySMQColumnOrderListonDemandJader", "cumulative": true, "fixedColumns": 3],
            [name: "System View", alertType: "Single Case Alert on Demand", filters: "{}", sorting: "{}", defaultValue: true, "columnList": "scaColumnOrderListOnDemand", "cumulative": false, "fixedColumns": 2],
            [name: "System View", alertType: "EVDAS Alert on Demand", filters: "{}", sorting: "{}", defaultValue: true, "columnList": "evdasColumnOrderListOnDemand", "cumulative": false, "fixedColumns": 3],
            [name: "System View", alertType: "Aggregate Case Alert - VAERS", filters: "{}", sorting: "{}", defaultValue: true, "columnList": "agaColumnOrderList", "cumulative": false, "fixedColumns": 6,"priorityRequired":true,"flagRequired":true],
            [name: "System View", alertType: "Aggregate Case Alert - SMQ VAERS", filters: "{}", sorting: "{}", defaultValue: true, "columnList": "agaGroupBySMQColumnOrderList", "cumulative": true, "fixedColumns": 5,"priorityRequired":true,"flagRequired":true],
            [name: "System View", alertType: "Aggregate Case Alert - VIGIBASE", filters: "{}", sorting: "{}", defaultValue: true, "columnList": "agaColumnOrderList", "cumulative": false, "fixedColumns": 6,"priorityRequired":true,"flagRequired":true],
            [name: "System View", alertType: "Aggregate Case Alert - SMQ VIGIBASE", filters: "{}", sorting: "{}", defaultValue: true, "columnList": "agaGroupBySMQColumnOrderList", "cumulative": true, "fixedColumns": 5,"priorityRequired":true,"flagRequired":true],
            [name: "System View", alertType: "Aggregate Case Alert - JADER", filters: "{}", sorting: "{}", defaultValue: true, "columnList": "jaderColumnOrderList", "cumulative": false, "fixedColumns": 6,"priorityRequired":true,"flagRequired":true],
            [name: "System View", alertType: "Aggregate Case Alert - SMQ JADER", filters: "{}", sorting: "{}", defaultValue: true, "columnList": "jaderColumnOrderList", "cumulative": true, "fixedColumns": 5,"priorityRequired":true,"flagRequired":true],

    ]


    agaColumnOrderListOnDemandVaers = [
            ["containerView": 1, "label": com.rxlogix.Constants.Commons.TAG, "name": "alertTags", isFilter: "true"],
            ["containerView": 1, "label": "Listed", "name": "listed", type: "text", isFilter: "true"],
            ["containerView": 1, "label": "New Count/Cum Count", "name": "newCount", type: "count", isFilter: "true"],
            ["containerView": 1, "label": "New Ser/Cum Ser", "name": "newSeriousCount", type: "count", isFilter: "true"],
            ["containerView": 1, "label": "New Fatal/Cum Fatal", "name": "newFatalCount", type: "count", isFilter: "true"],
            ["containerView": 3, "label": "PRR", "name": "prrValue", type: "count", isVisible: "true", isFilter: "${-> grails.util.Holders?.config?.statistics?.vaers?.enable?.prr}"],
            ["containerView": 3, "label": "ROR", "name": "rorValue", type: "count", isVisible: "true", isFilter: "${-> grails.util.Holders?.config?.statistics?.vaers?.enable?.ror}"],
            ["containerView": 1, "label": "EB05/EB95", "name": "eb05", type: "count", isVisible: "true", isFilter: "${-> grails.util.Holders?.config?.statistics?.vaers?.enable?.ebgm}"],
            ["containerView": 3, "label": "Chi-Square", "name": "chiSquare", type: "count", isVisible: "true", isFilter: "${-> grails.util.Holders?.config?.statistics?.vaers?.enable?.prr && grails.util.Holders?.config?.statistics?.vaers?.enable?.ror}"],
            ["containerView": 3, "label": "PRR LCI/PRR UCI", "name": "prrLCI", type: "count", isVisible: "true", isFilter: "${-> grails.util.Holders?.config?.statistics?.vaers?.enable?.prr}"],
            ["containerView": 3, "label": "ROR LCI/ROR UCI", "name": "rorLCI", type: "count", isVisible: "true", isFilter: "${-> grails.util.Holders?.config?.statistics?.vaers?.enable?.ror}"],
            ["containerView": 3, "label": "EBGM", "name": "ebgm", type: "count", isVisible: "true", isFilter: "${-> grails.util.Holders?.config?.statistics?.vaers?.enable?.ebgm}"],
            ["containerView": 3, "label": "New Paed/Cum Paed", "name": "newPediatricCount", type: "count", isFilter: "true"],
            ["containerView": 3, "label": "New Geria/Cum Geria", "name": "newGeriatricCount", type: "count", isFilter: "true"]
    ]

    agaGroupBySMQColumnOrderListonDemandVaers = [
            ["containerView": 1, "label": com.rxlogix.Constants.Commons.TAG, "name": "alertTags", isFilter: "true"],
            ["containerView": 1, "label": "New Count/Cum Count", "name": "newCount", type: "count", isFilter: "true"],
            ["containerView": 1, "label": "New Ser/Cum Ser", "name": "newSeriousCount", type: "count", isFilter: "true"],
            ["containerView": 1, "label": "New Fatal/Cum Fatal", "name": "newFatalCount", type: "count", isFilter: "true"],
            ["containerView": 3, "label": "PRR", "name": "prrValue", type: "count", isVisible: "true", isFilter: "${-> grails.util.Holders?.config?.statistics?.vaers?.enable?.prr}"],
            ["containerView": 3, "label": "ROR", "name": "rorValue", type: "count", isVisible: "true", isFilter: "${-> grails.util.Holders?.config?.statistics?.vaers?.enable?.ror}"],
            ["containerView": 1, "label": "EB05/EB95", "name": "eb05", type: "count", isVisible: "true", isFilter: "${-> grails.util.Holders?.config?.statistics?.vaers?.enable?.ebgm}"],
            ["containerView": 3, "label": "Chi-Square", "name": "chiSquare", type: "count", isVisible: "true", isFilter: "${-> grails.util.Holders?.config?.statistics?.vaers?.enable?.prr && grails.util.Holders?.config?.statistics?.vaers?.enable?.ror}"],
            ["containerView": 3, "label": "PRR LCI/PRR UCI", "name": "prrLCI", type: "count", isVisible: "true", isFilter: "${-> grails.util.Holders?.config?.statistics?.vaers?.enable?.prr}"],
            ["containerView": 3, "label": "ROR LCI/ROR UCI", "name": "rorLCI", type: "count", isVisible: "true", isFilter: "${-> grails.util.Holders?.config?.statistics?.vaers?.enable?.ror}"],
            ["containerView": 3, "label": "EBGM", "name": "ebgm", type: "count", isVisible: "true", isFilter: "${-> grails.util.Holders?.config?.statistics?.vaers?.enable?.ebgm}"],
            ["containerView": 3, "label": "New Paed/Cum Paed", "name": "newPediatricCount", type: "count", isFilter: "true"],
            ["containerView": 3, "label": "New Geria/Cum Geria", "name": "newGeriatricCount", type: "count", isFilter: "true"]
    ]

    scaVaersColumnOrderList = [
            ["containerView": 1, "label": com.rxlogix.Constants.Commons.TAG, "name": "alertTags"],
            ["containerView": 1, "label": "Receipt Date", "name": "caseInitReceiptDate"],
            ["containerView": 1, "label": "Product Name", "name": "productName"],
            ["containerView": 1, "label": "PT", "name": "pt"],
            ["containerView": 1, "label": "Outcome", "name": "outcome"],
            ["containerView": 1, "label": "Serious", "name": "serious"],
            ["containerView": 1, "label": "Death", "name": "death"],
            ["containerView": 1, "label": "Time To Onset", "name": "timeToOnset"],
            ["containerView": 3, "label": "Age", "name": "patientAge"],
            ["containerView": 3, "label": "Gender", "name": "gender"],
            ["containerView": 3, "label": "Batch/Lot#", "name": "batchLotNo"],
            ["containerView": 3, "label": "Comments", "name": "comments"],
    ]

}

configurations {
    agaColumnOrderListOnDemandJader = [
            ["containerView": 1, "label": com.rxlogix.Constants.Commons.TAG, "name": "alertTags", isFilter: "true"],
            ["containerView": 1, "label": "Listed", "name": "listed",type:"text", isFilter: "true"],
            ["containerView": 1, "label": "New Count/Cum Count", "name": "newCount",type:"count", isFilter: "true"],
            ["containerView": 1, "label": "New Fatal/Cum Fatal", "name": "newFatalCount",type:"count", isFilter: "true"],
            ["containerView": 1, "label": "EB05/EB95", "name": "eb05",type:"count", isVisible: "true",isFilter: "${-> Holders?.config?.statistics?.jader?.enable?.ebgm}"],
            ["containerView": 3, "label": "New Geria/Cum Geria", "name": "newGeriatricCount",type:"count", isFilter: "true"],
            ["containerView": 3, "label": "New Paed/Cum Paed", "name": "newPediatricCount",type:"count", isFilter: "true"],
            ["containerView": 3, "label": "PRR", "name": "prrValue",type: "count", isVisible: "true", isFilter: "${-> Holders?.config?.statistics?.jader?.enable?.prr}"],
            ["containerView": 3, "label": "ROR", "name": "rorValue",type:"count", isVisible: "true",isFilter: "${-> Holders?.config?.statistics?.jader?.enable?.ror}"],
            ["containerView": 3, "label": "EBGM", "name": "ebgm",type:"count",isVisible: "true", isFilter: "${-> Holders?.config?.statistics?.jader?.enable?.ebgm}"],
            ["containerView": 3, "label": "PRR LCI/PRR UCI", "name": "prrLCI",type:"count",isVisible: "true", isFilter: "${-> Holders?.config?.statistics?.jader?.enable?.prr}"],
            ["containerView": 3, "label": "ROR LCI/ROR UCI", "name": "rorLCI",type:"count",isVisible: "true", isFilter: "${-> Holders?.config?.statistics?.jader?.enable?.ror}"],
            ["containerView": 3, "label": "Chi-Square", "name": "chiSquare",type:"count", isVisible: "true", isFilter: "${-> Holders?.config?.statistics?.jader?.enable?.prr && Holders?.config?.statistics?.jader?.enable?.ror }"],
            ["containerView": 3, "label": "A", "name": "aValuer",type:"count",isVisible: "true", isFilter: "${-> Holders?.config?.statistics?.jader?.enable?.prr || Holders?.config?.statistics?.jader?.enable?.ror || Holders?.config?.statistics?.jader?.enable?.ebgm}"],
            ["containerView": 3, "label": "B", "name": "bValue",type:"count",isVisible: "true", isFilter: "${-> Holders?.config?.statistics?.jader?.enable?.prr || Holders?.config?.statistics?.jader?.enable?.ror || Holders?.config?.statistics?.jader?.enable?.ebgm }"],
            ["containerView": 3, "label": "C", "name": "cValue",type:"count",isVisible: "true", isFilter: "${-> Holders?.config?.statistics?.jader?.enable?.prr || Holders?.config?.statistics?.jader?.enable?.ror || Holders?.config?.statistics?.jader?.enable?.ebgm }"],
            ["containerView": 3, "label": "D", "name": "dValue",type:"count",isVisible: "true", isFilter: "${-> Holders?.config?.statistics?.jader?.enable?.prr || Holders?.config?.statistics?.jader?.enable?.ror || Holders?.config?.statistics?.jader?.enable?.ebgm}"],
            ["containerView": 3, "label": "E", "name": "eValue",type:"count",isVisible: "true", isFilter: "${-> Holders?.config?.statistics?.jader?.enable?.ebgm }"],
            ["containerView": 3, "label": "RR", "name": "rrValue",type:"count",isVisible: "true", isFilter: "${-> Holders?.config?.statistics?.jader?.enable?.ebgm }"],
    ]
    agaGroupBySMQColumnOrderListonDemandJader = [
            ["containerView": 1, "label": com.rxlogix.Constants.Commons.TAG, "name": "alertTags", isFilter: "true"],
            ["containerView": 1, "label": "New Count/Cum Count", "name": "newCount",type:"count", isFilter: "true"],
            ["containerView": 1, "label": "New Fatal/Cum Fatal", "name": "newFatalCount",type:"count", isFilter: "true"],
            ["containerView": 1, "label": "EB05/EB95", "name": "eb05",type:"count", isVisible: "true",isFilter: "${-> Holders?.config?.statistics?.jader?.enable?.ebgm}"],
            ["containerView": 3, "label": "New Geria/Cum Geria", "name": "newGeriatricCount",type:"count", isFilter: "true"],
            ["containerView": 3, "label": "New Paed/Cum Paed", "name": "newPediatricCount",type:"count", isFilter: "true"],
            ["containerView": 3, "label": "PRR", "name": "prrValue",type: "count", isVisible: "true", isFilter: "${-> Holders?.config?.statistics?.jader?.enable?.prr}"],
            ["containerView": 3, "label": "ROR", "name": "rorValue",type:"count", isVisible: "true",isFilter: "${-> Holders?.config?.statistics?.jader?.enable?.ror}"],
            ["containerView": 3, "label": "EBGM", "name": "ebgm",type:"count",isVisible: "true", isFilter: "${-> Holders?.config?.statistics?.jader?.enable?.ebgm}"],
            ["containerView": 3, "label": "PRR LCI/PRR UCI", "name": "prrLCI",type:"count",isVisible: "true", isFilter: "${-> Holders?.config?.statistics?.jader?.enable?.prr}"],
            ["containerView": 3, "label": "ROR LCI/ROR UCI", "name": "rorLCI",type:"count",isVisible: "true", isFilter: "${-> Holders?.config?.statistics?.jader?.enable?.ror}"],
            ["containerView": 3, "label": "Chi-Square", "name": "chiSquare",type:"count", isVisible: "true", isFilter: "${-> Holders?.config?.statistics?.jader?.enable?.prr && Holders?.config?.statistics?.jader?.enable?.ror }"],
            ["containerView": 3, "label": "A", "name": "aValuer",type:"count",isVisible: "true", isFilter: "${-> Holders?.config?.statistics?.jader?.enable?.prr || Holders?.config?.statistics?.jader?.enable?.ror || Holders?.config?.statistics?.jader?.enable?.ebgm}"],
            ["containerView": 3, "label": "B", "name": "bValue",type:"count",isVisible: "true", isFilter: "${-> Holders?.config?.statistics?.jader?.enable?.prr || Holders?.config?.statistics?.jader?.enable?.ror || Holders?.config?.statistics?.jader?.enable?.ebgm }"],
            ["containerView": 3, "label": "C", "name": "cValue",type:"count",isVisible: "true", isFilter: "${-> Holders?.config?.statistics?.jader?.enable?.prr || Holders?.config?.statistics?.jader?.enable?.ror || Holders?.config?.statistics?.jader?.enable?.ebgm }"],
            ["containerView": 3, "label": "D", "name": "dValue",type:"count",isVisible: "true", isFilter: "${-> Holders?.config?.statistics?.jader?.enable?.prr || Holders?.config?.statistics?.jader?.enable?.ror || Holders?.config?.statistics?.jader?.enable?.ebgm}"],
            ["containerView": 3, "label": "E", "name": "eValue",type:"count",isVisible: "true", isFilter: "${-> Holders?.config?.statistics?.jader?.enable?.ebgm }"],
            ["containerView": 3, "label": "RR", "name": "rrValue",type:"count",isVisible: "true", isFilter: "${-> Holders?.config?.statistics?.jader?.enable?.ebgm }"],
    ]
    scaJaderColumnOrderList = [
            ["containerView": 1, "label": com.rxlogix.Constants.Commons.TAG, "name": "alertTags"],
            ["containerView": 1, "label": "Product Name", "name": "productName"],
            ["containerView": 1, "label": "PT", "name": "pt"],
            ["containerView": 1, "label": "Generic Name", "name": "genericName", isFilter: true],
            ["containerView": 1, "label": "All PTs", "name": "allPt"],
            ["containerView": 1, "label": "All Suspect Products", "name": "suspProd"],
            ["containerView": 1, "label": "Gender", "name": "gender"],
            ["containerView": 1, "label": "Age", "name": "age"],
            ["containerView": 1, "label": "Initial Receipt Date", "name": "caseInitReceiptDate"],
            ["containerView": 1, "label": "Report Type", "name": "caseReportType"],
            ["containerView": 1, "label": "Indication", "name": "indication"],
            ["containerView": 1, "label": "Event Outcome", "name": "eventOutcome", isFilter: true],
            ["containerView": 3, "label": "All Conmeds", "name": "conComit"],
            ["containerView": 3, "label": "Death", "name": "death"],
            ["containerView": 3, "label": "Dose Details", "name": "doseDetails"],
            ["containerView": 3, "label": "HCP", "name": "reportersHcpFlag"],
            ["containerView": 3, "label": "Onset Date", "name": "eventOnsetDate", isFilter: true],
            ["containerView": 3, "label": "Patient Med Hist", "name": "patientMedHist", isFilter: true],
            ["containerView": 3, "label": "Rechallenge", "name": "rechallenge"],
            ["containerView": 3, "label": "Reporter Qualification", "name": "reporterQualification"],
            ["containerView": 3, "label": "Risk category", "name": "riskCategory"],
            ["containerView": 3, "label": "Therapy Dates", "name": "therapyDates"],
    ]
}

comment.template.counts = [
        [name:"Cum Count", enabled: "true"],
        [name: "Cum Fatal Count", enabled: "true"],
        [name: "Cum Geria Count", enabled: "true"],
        [name: "Cum Interacting Count", enabled: "true"],
        [name: "Cum Non-Ser Count", enabled: "true"],
        [name: "Cum Paed Count", enabled: "true"],
        [name: "Cum serious Count", enabled: "true"],
        [name: "Cum Spon Count", enabled: "true"],
        [name: "Cum Study Count", enabled: "true"],
        [name: "New Count", enabled: "true"],
        [name: "New Fatal Count", enabled: "true"],
        [name: "New Geria Count", enabled: "true"],
        [name: "New Interacting Count", enabled: "true"],
        [name: "New Non-Ser Count", enabled: "true"],
        [name: "New Paed Count", enabled: "true"],
        [name: "New serious Count", enabled: "true"],
        [name: "New Spon Count", enabled: "true"],
        [name: "New study Count", enabled: "true"],
        [name: "Cum Count (F)", enabled: "${-> grails.util.Holders?.config?.signal?.faers?.enabled }"],
        [name: "Cum Fatal Count (F)", enabled: "${-> grails.util.Holders?.config?.signal?.faers?.enabled }"],
        [name: "Cum Geria Count (F)", enabled: "${-> grails.util.Holders?.config?.signal?.faers?.enabled }"],
        [name: "Cum Interacting Count (F)", enabled: "${-> grails.util.Holders?.config?.signal?.faers?.enabled }"],
        [name: "Cum Non-Ser Count (F)", enabled: "${-> grails.util.Holders?.config?.signal?.faers?.enabled }"],
        [name: "Cum Paed Count (F)", enabled: "${-> grails.util.Holders?.config?.signal?.faers?.enabled }"],
        [name: "Cum serious Count (F)", enabled: "${-> grails.util.Holders?.config?.signal?.faers?.enabled }"],
        [name: "Cum Spon Count (F)", enabled: "${-> grails.util.Holders?.config?.signal?.faers?.enabled }"],
        [name: "Cum Study Count (F)", enabled: "${-> grails.util.Holders?.config?.signal?.faers?.enabled }"],
        [name: "New Count (F)", enabled: "${-> grails.util.Holders?.config?.signal?.faers?.enabled }"],
        [name: "New Fatal Count (F)", enabled: "${-> grails.util.Holders?.config?.signal?.faers?.enabled }"],
        [name: "New Geria Count (F)", enabled: "${-> grails.util.Holders?.config?.signal?.faers?.enabled }"],
        [name: "New Interacting Count (F)", enabled: "${-> grails.util.Holders?.config?.signal?.faers?.enabled }"],
        [name: "New Non-Ser Count (F)", enabled: "${-> grails.util.Holders?.config?.signal?.faers?.enabled }"],
        [name: "New Paed Count (F)", enabled: "${-> grails.util.Holders?.config?.signal?.faers?.enabled }"],
        [name: "New serious Count (F)", enabled: "${-> grails.util.Holders?.config?.signal?.faers?.enabled }"],
        [name: "New Spon Count (F)", enabled: "${-> grails.util.Holders?.config?.signal?.faers?.enabled }"],
        [name: "New study Count (F)", enabled: "${-> grails.util.Holders?.config?.signal?.faers?.enabled }"],
        [name: "Cum Count (VA)", enabled: "${-> grails.util.Holders?.config?.signal?.vaers?.enabled }"],
        [name: "Cum Fatal Count (VA)", enabled: "${-> grails.util.Holders?.config?.signal?.vaers?.enabled }"],
        [name: "Cum Geria Count (VA)", enabled: "${-> grails.util.Holders?.config?.signal?.vaers?.enabled }"],
        [name: "Cum Paed Count (VA)", enabled: "${-> grails.util.Holders?.config?.signal?.vaers?.enabled }"],
        [name: "Cum serious Count (VA)", enabled: "${-> grails.util.Holders?.config?.signal?.vaers?.enabled }"],
        [name: "New Count (VA)", enabled: "${-> grails.util.Holders?.config?.signal?.vaers?.enabled }"],
        [name: "New Fatal Count (VA)", enabled: "${-> grails.util.Holders?.config?.signal?.vaers?.enabled }"],
        [name: "New Geria Count (VA)", enabled: "${-> grails.util.Holders?.config?.signal?.vaers?.enabled }"],
        [name: "New Paed Count (VA)", enabled: "${-> grails.util.Holders?.config?.signal?.vaers?.enabled }"],
        [name: "New serious Count (VA)", enabled: "${-> grails.util.Holders?.config?.signal?.vaers?.enabled }"],
        [name: "New +RC Count (E)", enabled: "${-> grails.util.Holders?.config?.signal?.evdas?.enabled }"],
        [name: "New EEA Count (E)", enabled: "${-> grails.util.Holders?.config?.signal?.evdas?.enabled }"],
        [name: "New EV Count (E)", enabled: "${-> grails.util.Holders?.config?.signal?.evdas?.enabled }"],
        [name: "New Fatal Count (E)", enabled: "${-> grails.util.Holders?.config?.signal?.evdas?.enabled }"],
        [name: "New Geria Count (E)", enabled: "${-> grails.util.Holders?.config?.signal?.evdas?.enabled }"],
        [name: "New HCP Count (E)", enabled: "${-> grails.util.Holders?.config?.signal?.evdas?.enabled }"],
        [name: "New Lit Count (E)", enabled: "${-> grails.util.Holders?.config?.signal?.evdas?.enabled }"],
        [name: "New Med Err Count (E)", enabled: "${-> grails.util.Holders?.config?.signal?.evdas?.enabled }"],
        [name: "New obs Count (E)", enabled: "${-> grails.util.Holders?.config?.signal?.evdas?.enabled }"],
        [name: "New Paed Count (E)", enabled: "${-> grails.util.Holders?.config?.signal?.evdas?.enabled }"],
        [name: "New serious Count (E)", enabled: "${-> grails.util.Holders?.config?.signal?.evdas?.enabled }"],
        [name: "New Spon Count (E)", enabled: "${-> grails.util.Holders?.config?.signal?.evdas?.enabled }"],
        [name: "Total +RC Count (E)", enabled: "${-> grails.util.Holders?.config?.signal?.evdas?.enabled }"],
        [name: "Total EEA Count (E)", enabled: "${-> grails.util.Holders?.config?.signal?.evdas?.enabled }"],
        [name: "Total EV Count (E)", enabled: "${-> grails.util.Holders?.config?.signal?.evdas?.enabled }"],
        [name: "Total Fatal Count (E)", enabled: "${-> grails.util.Holders?.config?.signal?.evdas?.enabled }"],
        [name: "Total Geria Count (E)", enabled: "${-> grails.util.Holders?.config?.signal?.evdas?.enabled }"],
        [name: "Total HCP Count (E)", enabled: "${-> grails.util.Holders?.config?.signal?.evdas?.enabled }"],
        [name: "Total Lit Count (E)", enabled: "${-> grails.util.Holders?.config?.signal?.evdas?.enabled }"],
        [name: "Total Med Err Count (E)", enabled: "${-> grails.util.Holders?.config?.signal?.evdas?.enabled }"],
        [name: "Total obs Count (E)", enabled: "${-> grails.util.Holders?.config?.signal?.evdas?.enabled }"],
        [name: "Total Paed Count (E)", enabled: "${-> grails.util.Holders?.config?.signal?.evdas?.enabled }"],
        [name: "Total serious Count (E)", enabled: "${-> grails.util.Holders?.config?.signal?.evdas?.enabled }"],
        [name: "Total spont Asia (E)", enabled: "${-> grails.util.Holders?.config?.signal?.evdas?.enabled }"],
        [name: "Total spont Europe (E)", enabled: "${-> grails.util.Holders?.config?.signal?.evdas?.enabled }"],
        [name: "Total spont Japan (E)", enabled: "${-> grails.util.Holders?.config?.signal?.evdas?.enabled }"],
        [name: "Total spont N America (E)", enabled: "${-> grails.util.Holders?.config?.signal?.evdas?.enabled }"],
        [name: "Total spont Rest (E)", enabled: "${-> grails.util.Holders?.config?.signal?.evdas?.enabled }"],
        [name: "Total Spon Count (E)", enabled: "${-> grails.util.Holders?.config?.signal?.evdas?.enabled }"]
]

comment.template.score = [
        [name:"Chi square", enabled: "${-> grails.util.Holders?.config?.statistics?.enable?.prr && grails.util.Holders?.config?.statistics?.enable?.ror }"],
        [name:"DSS Score", enabled:"${-> grails.util.Holders?.config?.statistics?.enable?.dss}"],
        [name:"EB05", enabled: "${-> grails.util.Holders?.config?.statistics?.enable?.ebgm }"],
        [name:"EB95", enabled: "${-> grails.util.Holders?.config?.statistics?.enable?.ebgm }"],
        [name:"EBGM", enabled: "${-> grails.util.Holders?.config?.statistics?.enable?.ebgm }"],
        [name:"PRR", enabled: "${-> grails.util.Holders?.config?.statistics?.enable?.prr }"],
        [name:"PRR LCI", enabled: "${-> grails.util.Holders?.config?.statistics?.enable?.prr }"],
        [name:"PRR UCI", enabled: "${-> grails.util.Holders?.config?.statistics?.enable?.prr }"],
        [name:"ROR", enabled: "${-> grails.util.Holders?.config?.statistics?.enable?.ror }"], // check for iROR???
        [name:"ROR LCI", enabled: "${-> grails.util.Holders?.config?.statistics?.enable?.ror }"],
        [name:"ROR UCI", enabled: "${-> grails.util.Holders?.config?.statistics?.enable?.ror }"],
        [name:"SOC", enabled:'true'],
        [name:"+ve Rechallenge", enabled:'true'],
        [name:"+ve Dechallenge",enabled: 'true'],
        [name:"Pregnancy", enabled:'true'],
        [name:"Trend Type", enabled:'true'],
        [name:"Categories", enabled:'true'],
        [name:"Listed", enabled:'true'],
        [name:"${-> grails.util.Holders?.config?.statistics?.enable?.dss && grails.util.Holders?.config?.dss?.enable?.autoProposed ? "Rationale(Prior Review/DSS)" : 'DSS'}", enabled:"${-> grails.util.Holders?.config?.statistics?.enable?.dss}"],
        [name:"Chi square (F)", enabled: "${-> grails.util.Holders?.config?.signal?.faers?.enabled && grails.util.Holders?.config?.statistics?.faers?.enable?.prr && grails.util.Holders?.config?.statistics?.faers?.enable?.ror }"],
        [name:"EB05 (F)", enabled: "${-> grails.util.Holders?.config?.signal?.faers?.enabled && grails.util.Holders?.config?.statistics?.faers?.enable?.ebgm }"],
        [name:"EB95 (F)", enabled: "${-> grails.util.Holders?.config?.signal?.faers?.enabled && grails.util.Holders?.config?.statistics?.faers?.enable?.ebgm }"],
        [name:"EBGM (F)", enabled: "${-> grails.util.Holders?.config?.signal?.faers?.enabled && grails.util.Holders?.config?.statistics?.faers?.enable?.ebgm }"],
        [name:"PRR (F)", enabled: "${-> grails.util.Holders?.config?.signal?.faers?.enabled && grails.util.Holders?.config?.statistics?.faers?.enable?.prr }"],
        [name:"PRR LCI (F)", enabled: "${-> grails.util.Holders?.config?.signal?.faers?.enabled && grails.util.Holders?.config?.statistics?.faers?.enable?.prr }"],
        [name:"PRR UCI (F)",enabled: "${->  grails.util.Holders?.config?.signal?.faers?.enabled && grails.util.Holders?.config?.statistics?.faers?.enable?.prr }"],
        [name:"ROR (F)", enabled: "${-> grails.util.Holders?.config?.signal?.faers?.enabled && grails.util.Holders?.config?.statistics?.faers?.enable?.ror }"],
        [name:"ROR LCI (F)", enabled: "${-> grails.util.Holders?.config?.signal?.faers?.enabled && grails.util.Holders?.config?.statistics?.faers?.enable?.ror }"],
        [name:"ROR UCI (F)", enabled: "${-> grails.util.Holders?.config?.signal?.faers?.enabled && grails.util.Holders?.config?.statistics?.faers?.enable?.ror }"],
        [name:"+ve Rechallenge (F)", enabled: "${-> grails.util.Holders?.config?.signal?.faers?.enabled }"],
        [name:"+ve Dechallenge (F)", enabled: "${-> grails.util.Holders?.config?.signal?.faers?.enabled }"],
        [name:"Pregnancy (F)", enabled: "${-> grails.util.Holders?.config?.signal?.faers?.enabled }"],
        [name:"Trend Type (F)", enabled: "${-> grails.util.Holders?.config?.signal?.faers?.enabled }"],
        [name:"Chi square (VA)", enabled: "${-> grails.util.Holders?.config?.signal?.vaers?.enabled && grails.util.Holders?.config?.statistics?.vaers?.enable?.prr && grails.util.Holders?.config?.statistics?.vaers?.enable?.ror }"],
        [name:"EB05 (VA)",enabled: "${-> grails.util.Holders?.config?.signal?.vaers?.enabled && grails.util.Holders?.config?.statistics?.vaers?.enable?.ebgm }"],
        [name:"EB95 (VA)", enabled: "${-> grails.util.Holders?.config?.signal?.vaers?.enabled && grails.util.Holders?.config?.statistics?.vaers?.enable?.ebgm }"],
        [name:"EBGM (VA)", enabled: "${-> grails.util.Holders?.config?.signal?.vaers?.enabled && grails.util.Holders?.config?.statistics?.vaers?.enable?.ebgm }"],
        [name:"PRR (VA)", enabled: "${-> grails.util.Holders?.config?.signal?.vaers?.enabled && grails.util.Holders?.config?.statistics?.vaers?.enable?.prr }"],
        [name:"PRR LCI (VA)", enabled: "${-> grails.util.Holders?.config?.signal?.vaers?.enabled && grails.util.Holders?.config?.statistics?.vaers?.enable?.prr }"],
        [name:"PRR UCI (VA)", enabled: "${-> grails.util.Holders?.config?.signal?.vaers?.enabled && grails.util.Holders?.config?.statistics?.vaers?.enable?.prr }"],
        [name:"ROR (VA)", enabled: "${-> grails.util.Holders?.config?.signal?.vaers?.enabled && grails.util.Holders?.config?.statistics?.vaers?.enable?.ror }"],
        [name:"ROR LCI (VA)", enabled: "${-> grails.util.Holders?.config?.signal?.vaers?.enabled && grails.util.Holders?.config?.statistics?.vaers?.enable?.ror }"],
        [name:"ROR UCI (VA)", enabled: "${-> grails.util.Holders?.config?.signal?.vaers?.enabled && grails.util.Holders?.config?.statistics?.vaers?.enable?.ror }"],
        [name:"ROR (E)", enabled: "${-> grails.util.Holders?.config?.signal?.evdas?.enabled }"],
        [name:"SDR (E)", enabled: "${-> grails.util.Holders?.config?.signal?.evdas?.enabled }"],
        [name:"ROR(Asia) (E)", enabled: "${-> grails.util.Holders?.config?.signal?.evdas?.enabled }"],
        [name:"ROR(Europe) (E)",enabled: "${->  grails.util.Holders?.config?.signal?.evdas?.enabled }"],
        [name:"ROR(Japan) (E)", enabled: "${-> grails.util.Holders?.config?.signal?.evdas?.enabled }"],
        [name:"ROR(North America) (E)", enabled: "${-> grails.util.Holders?.config?.signal?.evdas?.enabled }"],
        [name:"ROR(Rest) (E)", enabled: "${-> grails.util.Holders?.config?.signal?.evdas?.enabled }"],
        [name:"IME/DME (E)",enabled: "${->  grails.util.Holders?.config?.signal?.evdas?.enabled }"]
]

advancedFilter.aliasPropertiesMap = [
        'ptList'            : ['SCA_PT', 'SINGLE_ALERT_PT', 'SINGLE_ALERT_ID'],
        'conComitList'      : ['ALERT_CON_COMIT', 'SINGLE_ALERT_CON_COMIT', 'SINGLE_ALERT_ID'],
        'suspectProductList': ['SCA_PRODUCT_NAME', 'SINGLE_ALERT_SUSP_PROD', 'SINGLE_ALERT_ID'],
        'medErrorPtList'    : ['SCA_MED_ERROR', 'SINGLE_ALERT_MED_ERR_PT_LIST', 'SINGLE_ALERT_ID'],
        'aggImpEventList'   : ['AGA_IMP_EVENTS', 'AGG_ALERT_IMP_EVENT_LIST', 'AGG_ALERT_ID'],
        'evImpEventList'    : ['EVDAS_IMP_EVENTS', 'EVDAS_ALERT_IMP_EVENT_LIST', 'EVDAS_ALERT_ID'],
        'caseNarrative'     : ['CASE_NARRATIVE'],
        'indication'        : ['SCA_INDICATION', 'SINGLE_ALERT_INDICATION_LIST', 'SINGLE_ALERT_ID'],
        'causeOfDeath'      : ['SCA_CAUSE_OF_DEATH', 'SINGLE_ALERT_CAUSE_OF_DEATH', 'SINGLE_ALERT_ID'],
        'patientMedHist'    : ['SCA_PAT_MED_HIST', 'SINGLE_ALERT_PAT_MED_HIST', 'SINGLE_ALERT_ID'],
        'patientHistDrugs'  : ['SCA_PAT_HIST_DRUGS', 'SINGLE_ALERT_PAT_HIST_DRUGS', 'SINGLE_ALERT_ID'],
        'batchLotNo'        : ['SCA_BATCH_LOT_NO', 'SINGLE_ALERT_BATCH_LOT_NO', 'SINGLE_ALERT_ID'],
        'caseClassification': ['SCA_CASE_CLASSIFICATION', 'SINGLE_ALERT_CASE_CLASSIFI', 'SINGLE_ALERT_ID'],
        'therapyDates'      : ['SCA_THERAPY_DATES', 'SINGLE_ALERT_THERAPY_DATES', 'SINGLE_ALERT_ID'],
        'doseDetails'       : ['SCA_DOSE_DETAILS', 'SINGLE_ALERT_DOSE_DETAILS', 'SINGLE_ALERT_ID'],
        'primSuspProdList'  : ['SCA_PRIM_SUSP', 'SINGLE_ALERT_PRIM_SUSP', 'SINGLE_ALERT_ID'],
        'primSuspPaiList'   : ['SCA_PRIM_PAI', 'SINGLE_ALERT_PRIM_PAI', 'SINGLE_ALERT_ID'],
        'paiAllList'        : ['SCA_ALL_PAI', 'SINGLE_ALERT_ALL_PAI', 'SINGLE_ALERT_ID'],
        'allPtList'         : ['SCA_ALL_PT', 'SINGLE_ALERT_ALL_PT', 'SINGLE_ALERT_ID'],
        'genericName'       :  ['GENERIC_NAME', 'SINGLE_ALERT_GENERIC_NAME', 'SINGLE_ALERT_ID'],
        'allPTsOutcomeList' : ['ALLPTS_OUTCOME', 'SINGLE_ALERT_ALLPT_OUT_COME', 'SINGLE_ALERT_ID']
]
advancedFilter.onDemand.aliasPropertiesMap = [
        'ptList'            : ['PT', 'SINGLE_ALERT_OD_PT','SINGLE_ALERT_OD_ID'],
        'conComitList'      : ['CON_COMIT', 'SINGLE_ALERT_OD_CON_COMIT','SINGLE_ALERT_OD_ID'],
        'suspectProductList': ['PRODUCT_NAME','SINGLE_ALERT_OD_SUSP_PROD','SINGLE_ALERT_OD_ID'],
        'medErrorPtList'    : ['MED_ERROR','SINGLE_ALERT_OD_MED_ERR','SINGLE_ALERT_OD_ID'],
        'aggImpEventList'   : ['AGA_ON_DEMAND_IMP_EVENTS','AOD_ALERT_IMP_EVENT_LIST','AGG_ON_DEMAND_ALERT_ID'],
        'evImpEventList'    : ['EVDAS_ON_DEMAND_IMP_EVENTS','EOD_ALERT_IMP_EVENT_LIST','EVDAS_ON_DEMAND_ALERT_ID'],
        'caseNarrative'     : ['CASE_NARRATIVE'],
        'indication'        : ['SCA_INDICATION', 'SINGLE_DEMAND_INDICATION_LIST', 'SINGLE_ALERT_ID'],
        'causeOfDeath'      : ['SCA_CAUSE_OF_DEATH', 'SINGLE_DEMAND_CAUSE_OF_DEATH', 'SINGLE_ALERT_ID'],
        'patientMedHist'    : ['SCA_PAT_MED_HIST', 'SINGLE_DEMAND_PAT_MED_HIST', 'SINGLE_ALERT_ID'],
        'patientHistDrugs'  : ['SCA_PAT_HIST_DRUGS', 'SINGLE_DEMAND_PAT_HIST_DRUGS', 'SINGLE_ALERT_ID'],
        'batchLotNo'        : ['SCA_BATCH_LOT_NO', 'SINGLE_DEMAND_BATCH_LOT_NO', 'SINGLE_ALERT_ID'],
        'caseClassification': ['SCA_CASE_CLASSIFICATION', 'SINGLE_DEMAND_CASE_CLASSIFI', 'SINGLE_ALERT_ID'],
        'therapyDates'      : ['SCA_THERAPY_DATES', 'SINGLE_DEMAND_THERAPY_DATES', 'SINGLE_ALERT_ID'],
        'doseDetails'       : ['SCA_DOSE_DETAILS', 'SINGLE_DEMAND_DOSE_DETAILS', 'SINGLE_ALERT_ID'],
        'primSuspProdList'  : ['SCA_PRIM_SUSP', 'SINGLE_DEMAND_PRIM_SUSP', 'SINGLE_ALERT_ID'],
        'primSuspPaiList'   : ['SCA_PRIM_PAI', 'SINGLE_DEMAND_PRIM_PAI', 'SINGLE_ALERT_ID'],
        'paiAllList'        : ['SCA_ALL_PAI', 'SINGLE_DEMAND_ALL_PAI', 'SINGLE_ALERT_ID'],
        'allPtList'         : ['SCA_ALL_PT', 'SINGLE_DEMAND_ALL_PT', 'SINGLE_ALERT_ID'],
        'genericName'       : ['GENERIC_NAME', 'SIG_DMD_ALRT_GENERIC_NAME', 'SINGLE_ALERT_ID'],
        'allPTsOutcomeList' : ['ALLPTS_OUTCOME', 'SIG_DMD_ALRT_ALLPT_OUT_COME', 'SINGLE_ALERT_ID']
]

pvreports.api.delete.configuration = "/reports/public/api/softDeleteConfiguration"

testBed.automation.checkIfFileExist = "/api/checkIfFileExists/"
testBed.automation.uploadTestCases = "/api/uploadTestCases/"
testBed.automation.runAlerts = "/api/runAlerts/"
