package com.rxlogix.config

enum ActivityTypeValue implements Serializable {

    CategoryUpdated('CategoryUpdated'),
    DocumentRemovedFromAlert('DocumentRemovedFromAlert'),
    AttachmentAdded('AttachmentAdded'),
    AttachmentUpdated('AttachmentUpdated'),
    AttachmentRemoved('AttachmentRemoved'),
    ReferenceAdded('ReferenceAdded'),
    ReferenceUpdated('ReferenceUpdated'),
    ReferenceRemoved('ReferenceRemoved'),
    DocumentAddedToAlert('DocumentAddedToAlert'),
    WorkflowStateChange('WorkflowChange'),
    DispositionChange('DispositionChange'),
    DocumentUpdated('DocumentUpdated'),
    UserGroupChange('USerGroupChange'),
    PriorityChange('PriorityChange'),
    ActionCreated('ActionCreated'),
    ActionChange('ActionChange'),
    AssignedToChange('AssignedToChange'),
    Misc('Miscellaneous'),
    CommentAdded('CommentAdded'),
    AssessmentNoteAdded('AssessmentNoteAdded'),
    CommentUpdated('CommentUpdated'),
    CaseDissociated('CaseDissociated'),
    CaseAssociated('CaseAssociated'),
    CaseAdded('CaseAdded'),
    CommentRemoved('CommentRemoved'),
    MeetingCreated('MeetingCreated'),
    MeetingUpdated('MeetingUpdated'),
    MeetingCancelled('MeetingCancelled'),
    TopicAdded('TopicAdded'),
    SignalUpdated('SignalUpdated'),
    TopicMigrated('TopicMigrated'),
    DocumentAddedToSignal('DocumentAddedToSignal'),
    DocumentRemovedFromSignal('DocumentRemovedFromSignal'),
    AdhocAlertDissociated('AdhocAlertDissociated'),
    AdhocAlertAssociated('AdhocAlertAssociated'),
    PECDissociated('PECDissociated'),
    PECAssociated('PECAssociated'),
    ReasonForDelay('ReasonForDelay'),
    TagAdded('TagAdded'),
    TagRemoved('TagRemoved'),
    CaseSeriesSaved('CaseSeriesSaved'),
    ReportGenerated('ReportGenerated'),
    LiteratureAlertAssociated('LiteratureAlertAssociated'),
    JustificationChange('JustificationChange'),
    StatusDate('StatusDate'),
    SignalMigrated('SignalMigrated'),
    SignalCreated('SignalCreated'),
    SignalAdded('SignalAdded'),
    CategoryAdded('CategoryAdded'),
    CategoryRemoved('CategoryRemoved'),
    RMMAdded('RMMAdded'),
    RMMUpdated('RMMUpdated'),
    CommunicationAdded('CommunicationAdded'),
    CommunicationUpdated('CommunicationUpdated'),
    RMMDeleted('RMMDeleted'),
    CommunicationDeleted('CommunicationDeleted'),
    UndoAction('UndoAction'),
    CommunicationSent("CommunicationSent"),
    AlertLinked("AlertLinked"),
    SharedWithChange('SharedWithChange')
    String value

    ActivityTypeValue(v) {value = v}

}
