azure_openai_4k:
  api_type: API_TYPE_4K
  api_version: API_VERSION_4K
  api_base: API_BASE_URL_4K
  api_key: API_KEY_4K
  engine: APT_ENGINE_4K

azure_openai_16k:
  api_type: API_TYPE_16K
  api_version: API_VERSION_4K
  api_base: API_BASE_URL_16K
  api_key: API_KEY_16K
  engine: APT_ENGINE_16K

azure_openai_gpt4:
  api_type: API_TYPE_GPT4
  api_version: API_VERSION_GPT4
  api_base: API_BASE_URL_GPT4
  api_key: API_KEY_GPT4
  engine: APT_ENGINE_GPT4

azure_openai_gpt4O:
  api_type: API_TYPE_GPT4O
  api_version: API_VERSION_GPT4O
  api_base: API_BASE_URL_GPT4O
  api_key: API_KEY_GPT4O
  engine: APT_ENGINE_GPT40

max_tries: 3
sleep_before_retry: 2
max_requests_openai: 1
max_timeout_4k: 100
max_timeout: 300
input_max_tokens: 7000