package com.rxlogix.enums

enum AdjustmentTypeEnum {

    ALERT_PER_SKIPPED_EXECUTION('ALERT_PER_SKIPPED_EXECUTION'),
    SINGLE_ALERT_FOR_ALL_SKIPPED_EXECUTION('SINGLE_ALERT_FOR_ALL_SKIPPED_EXECUTION'),
    MANUAL_AUTO_ADJUSTMENT('MANUAL_AUTO_ADJUSTMENT'),
    FAILED_ALERT_PER_SKIPPED_EXECUTION('FAILED_ALERT_PER_SKIPPED_EXECUTION'),
    FAILED_SINGLE_ALERT_FOR_ALL_SKIPPED_EXECUTION('FAILED_SINGLE_ALERT_FOR_ALL_SKIPPED_EXECUTION'),
    FAILED_MANUAL_AUTO_ADJUSTMENT('FAILED_MANUAL_AUTO_ADJUSTMENT')

    private final String val

    AdjustmentTypeEnum(String val) {
        this.val = val
    }

    String value() { return val }
}