name: CodeNarc Analysis

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  codenarc:
    name: Run CodeNarc
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Java environment
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: temurin

      # Step 3: Set up Gradle
      - name: Set up Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.6

      # Step 4: Run CodeNarc analysis
      - name: Run CodeNarc
        run: ./gradlew codenarcMain

      # Step 5: Upload CodeNarc report
      - name: Upload CodeNarc report
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: codenarc-report
          path: build/reports/codenarc/codenarcMain.html
